DROP DATABASE IF EXISTS 201_assign4;
CREATE DATABASE 201_assign4;
USE 201_assign4;
CREATE TABLE FavoriteStock (
  Username VARCHAR(45) NOT NULL,
  Ticker VARCHAR(45) NULL);
CREATE TABLE SaleRec(
  idSale INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(45) NULL,
  TickerName VARCHAR(45) NULL,
  Amount DOUBLE NULL DEFAULT 0,
  Price DOUBLE NULL DEFAULT 0,
  isPurchase SMALLINT NULL,
  PRIMARY KEY (idSale));
CREATE TABLE UserInfo (
  Username VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NULL,
  Email VARCHAR(45) NULL,
  Balance DOUBLE NULL DEFAULT 50000,
  PRIMARY KEY (Username));

  